number=[10,0,4,5]
mix_num=[10,'zakiya',10.5,"khan"]
print(mix_num)
print(len(mix_num))
print(number[3])
print(number[1:3])
print(number[0:5:3])
number.sort()
print(number)
number.reverse()
print(number)
print(max(number))
number.append(45)
print(number)
number.insert(0,3)
print(number)
number[1:4]={30,31,32,33}
print(number)
number.remove(0)
print(number)

